package wsfecred.afip.gob.ar.fecredservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.5.0
 * 2023-05-22T11:18:27.603-03:00
 * Generated source version: 3.5.0
 *
 */
@WebService(targetNamespace = "http://ar.gob.afip.wsfecred/FECredService/", name = "FECredServicePortType")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface FECredServicePortType {

    @WebMethod(action = "http://ar.gob.afip.wsfecred/FECredService/obtenerRemitos")
    @WebResult(name = "obtenerRemitosResponse", targetNamespace = "http://ar.gob.afip.wsfecred/FECredService/", partName = "parameters")
    public ObtenerRemitosResponseType obtenerRemitos(

        @WebParam(partName = "parameters", name = "obtenerRemitosRequest", targetNamespace = "http://ar.gob.afip.wsfecred/FECredService/")
        ObtenerRemitosRequestType parameters
    );

    /**
     * Método que permite al Vendedor solicitar la transeferencia (al Agente de Depósito Colectivo) de
     * 				la factura de crédito con el saldo resultante de la cuenta corriente vinculada aceptada por el comprador, debiendo
     * 				indicar la Cuenta del Agente de Deposito Colectivo.
     * 			
     */
    @WebMethod(action = "http://ar.gob.afip.wsfecred/FECredService/informarFacturaAgtDptoCltv")
    @WebResult(name = "informarFacturaAgtDptoCltvResponse", targetNamespace = "http://ar.gob.afip.wsfecred/FECredService/", partName = "parameters")
    public OperacionFECredResponseType informarFacturaAgtDptoCltv(

        @WebParam(partName = "parameters", name = "informarFacturaAgtDptoCltvRequest", targetNamespace = "http://ar.gob.afip.wsfecred/FECredService/")
        InformarFacturaAgtDptoCltvRequestType parameters
    );

    @WebMethod(action = "http://ar.gob.afip.wsfecred/FECredService/consultarHistorialEstadosComprobante")
    @WebResult(name = "consultarHistorialEstadosComprobanteResponse", targetNamespace = "http://ar.gob.afip.wsfecred/FECredService/", partName = "parameters")
    public ConsultarHistorialEstadosComprobanteResponseType consultarHistorialEstadosComprobante(

        @WebParam(partName = "parameters", name = "consultarHistorialEstadosComprobanteRequest", targetNamespace = "http://ar.gob.afip.wsfecred/FECredService/")
        ConsultarHistorialEstadosComprobanteRequestType parameters
    );

    /**
     * Método que permite obtener el detalle y composición de una cuenta corriente.
     * 			
     */
    @WebMethod(action = "http://ar.gob.afip.wsfecred/FECredService/consultarCtaCte")
    @WebResult(name = "consultarCtaCteResponse", targetNamespace = "http://ar.gob.afip.wsfecred/FECredService/", partName = "parameters")
    public ConsultarCtaCteResponseType consultarCtaCte(

        @WebParam(partName = "parameters", name = "consultarCtaCteRequest", targetNamespace = "http://ar.gob.afip.wsfecred/FECredService/")
        ConsultarCtaCteRequestType parameters
    );

    /**
     * Método que permite listar los tipos de  motivos de rechazo habilitados para una cta. cte.
     * 			
     */
    @WebMethod(action = "http://ar.gob.afip.wsfecred/FECredService/consultarTiposMotivosRechazo")
    @WebResult(name = "consultarTiposMotivosRechazoResponse", targetNamespace = "http://ar.gob.afip.wsfecred/FECredService/", partName = "parameters")
    public ConsultarCodigoDescripcionResponseType consultarTiposMotivosRechazo(

        @WebParam(partName = "parameters", name = "consultarTiposMotivosRechazoRequest", targetNamespace = "http://ar.gob.afip.wsfecred/FECredService/")
        ConsultarCodigoDescripcionRequestType parameters
    );

    /**
     * Metodo dummy.
     */
    @WebMethod(action = "http://ar.gob.afip.wsfecred/FECredService/dummy")
    @WebResult(name = "dummyResponse", targetNamespace = "http://ar.gob.afip.wsfecred/FECredService/", partName = "parameters")
    public DummyResponseType dummy()
;

    @WebMethod(action = "http://ar.gob.afip.wsfecred/FECredService/consultarMontoObligadoRecepcion")
    @WebResult(name = "consultarMontoObligadoRecepcionResponse", targetNamespace = "http://ar.gob.afip.wsfecred/FECredService/", partName = "parameters")
    public ConsultarMontoObligadoRecepcionResponseType consultarMontoObligadoRecepcion(

        @WebParam(partName = "parameters", name = "consultarMontoObligadoRecepcionRequest", targetNamespace = "http://ar.gob.afip.wsfecred/FECredService/")
        ConsultarMontoObligadoRecepcionRequestType parameters
    );

    /**
     * Método que permite al Vendedor consultar sus cuentas en sus Agentes de Deposito Colectivo
     * 			
     */
    @WebMethod(action = "http://ar.gob.afip.wsfecred/FECredService/consultarCuentasEnAgtDptoCltv")
    @WebResult(name = "consultarCuentasEnAgtDptoCltvResponse", targetNamespace = "http://ar.gob.afip.wsfecred/FECredService/", partName = "parameters")
    public ConsultarCuentasEnAgtDptoCltvResponseType consultarCuentasEnAgtDptoCltv(

        @WebParam(partName = "parameters", name = "consultarCuentasEnAgtDptoCltvRequest", targetNamespace = "http://ar.gob.afip.wsfecred/FECredService/")
        ConsultarCuentasEnAgtDptoCltvRequestType parameters
    );

    /**
     * Método que permite obtener información sobre los comprobates Emitidos y Recibidos.
     * 			
     */
    @WebMethod(action = "http://ar.gob.afip.wsfecred/FECredService/consultarComprobantes")
    @WebResult(name = "consultarComprobantesResponse", targetNamespace = "http://ar.gob.afip.wsfecred/FECredService/", partName = "parameters")
    public ConsultarComprobantesResponseType consultarComprobantes(

        @WebParam(partName = "parameters", name = "consultarComprobantesRequest", targetNamespace = "http://ar.gob.afip.wsfecred/FECredService/")
        ConsultarComprobanteRequestType parameters
    );

    @WebMethod(action = "http://ar.gob.afip.wsfecred/FECredService/consultarTiposAjustesOperacion")
    @WebResult(name = "consultarTiposAjustesOperacionResponse", targetNamespace = "http://ar.gob.afip.wsfecred/FECredService/", partName = "parameters")
    public ConsultarCodigoDescripcionResponseType consultarTiposAjustesOperacion(

        @WebParam(partName = "parameters", name = "consultarTiposAjustesOperacionRequest", targetNamespace = "http://ar.gob.afip.wsfecred/FECredService/")
        ConsultarCodigoDescripcionRequestType parameters
    );

    /**
     * Método por el cual el Comprador informa que le ha cancelado (pagado) totalmente la deuda al
     * 				vendedor, debiendo indicar la forma de pago.Solo puede cancelar las aceptadas dentros de los plazos establecidos
     * 			
     */
    @WebMethod(action = "http://ar.gob.afip.wsfecred/FECredService/informarCancelacionTotalFECred")
    @WebResult(name = "informarCancelacionTotalFECredResponse", targetNamespace = "http://ar.gob.afip.wsfecred/FECredService/", partName = "parameters")
    public OperacionFECredResponseType informarCancelacionTotalFECred(

        @WebParam(partName = "parameters", name = "informarCancelacionTotalFECredRequest", targetNamespace = "http://ar.gob.afip.wsfecred/FECredService/")
        InformarCancelacionTotalFECredRequestType parameters
    );

    /**
     * Método que permite al Comprador Rechazar la Cta. Cte. de una Factura de Crédito debiendo indicar
     * 				el motivo del rechazo.
     * 			
     */
    @WebMethod(action = "http://ar.gob.afip.wsfecred/FECredService/rechazarFECred")
    @WebResult(name = "rechazarFECredResponse", targetNamespace = "http://ar.gob.afip.wsfecred/FECredService/", partName = "parameters")
    public OperacionFECredResponseType rechazarFECred(

        @WebParam(partName = "parameters", name = "rechazarFECredRequest", targetNamespace = "http://ar.gob.afip.wsfecred/FECredService/")
        RechazarFECredRequestType parameters
    );

    /**
     * Método que permite al Comprador rechazar Notas de Débito / Crédito individualmente para
     * 				desafectarlas del cálculo del saldo de la Cta. Cte. vinculada.
     * 			
     */
    @WebMethod(action = "http://ar.gob.afip.wsfecred/FECredService/rechazarNotaDC")
    @WebResult(name = "rechazarNotaDCResponse", targetNamespace = "http://ar.gob.afip.wsfecred/FECredService/", partName = "parameters")
    public RechazarNotaDCResponseType rechazarNotaDC(

        @WebParam(partName = "parameters", name = "rechazarNotaDCRequest", targetNamespace = "http://ar.gob.afip.wsfecred/FECredService/")
        RechazarNotaDCRequestType parameters
    );

    /**
     * Método que permite obtener las cuentas corrientes que fueron generadas a partir de la
     * 				facturación, que coinciden con los parámetros de búsqueda.
     * 			
     */
    @WebMethod(action = "http://ar.gob.afip.wsfecred/FECredService/consultarCtasCtes")
    @WebResult(name = "consultarCtasCtesResponse", targetNamespace = "http://ar.gob.afip.wsfecred/FECredService/", partName = "parameters")
    public ConsultarCtasCtesResponseType consultarCtasCtes(

        @WebParam(partName = "parameters", name = "consultarCtasCtesRequest", targetNamespace = "http://ar.gob.afip.wsfecred/FECredService/")
        ConsultarCtasCtesRequestType parameters
    );

    /**
     * Método que permite al Comprador Aceptar el saldo actual de la Cta. Cte. de una Factura de Crédito
     * 				pudiendo indicar: pagos parciales, retenciones y/o embargos.
     * 			
     */
    @WebMethod(action = "http://ar.gob.afip.wsfecred/FECredService/aceptarFECred")
    @WebResult(name = "aceptarFECredResponse", targetNamespace = "http://ar.gob.afip.wsfecred/FECredService/", partName = "parameters")
    public OperacionFECredResponseType aceptarFECred(

        @WebParam(partName = "parameters", name = "aceptarFECredRequest", targetNamespace = "http://ar.gob.afip.wsfecred/FECredService/")
        AceptarFECredRequestType parameters
    );

    /**
     * Método que permite listar los tipos de formas de pago habilitados para una factura de crédito.
     * 			
     */
    @WebMethod(action = "http://ar.gob.afip.wsfecred/FECredService/consultarTiposFormasCancelacion")
    @WebResult(name = "consultarTiposFormasCancelacionResponse", targetNamespace = "http://ar.gob.afip.wsfecred/FECredService/", partName = "parameters")
    public ConsultarCodigoDescripcionResponseType consultarTiposFormasCancelacion(

        @WebParam(partName = "parameters", name = "consultarTiposFormasCancelacionRequest", targetNamespace = "http://ar.gob.afip.wsfecred/FECredService/")
        ConsultarCodigoDescripcionRequestType parameters
    );

    /**
     * Método que permite a partir de una CUIT conocer su obligación respecto a la emisión o recepción
     * 				de facturas de créditos
     * 			
     */
    @WebMethod(action = "http://ar.gob.afip.wsfecred/FECredService/consultarObligadoRecepcion")
    @WebResult(name = "consultarObligadoRecepcionResponse", targetNamespace = "http://ar.gob.afip.wsfecred/FECredService/", partName = "parameters")
    public ConsultarObligadoRecepcionResponseType consultarObligadoRecepcion(

        @WebParam(partName = "parameters", name = "consultarObligadoRecepcionRequest", targetNamespace = "http://ar.gob.afip.wsfecred/FECredService/")
        ConsultarObligadoRecepcionRequestType parameters
    );

    /**
     * Método que permite consultar los tipos de retenciones habilitadas con sus respectivos porcentajes.
     * 			
     */
    @WebMethod(action = "http://ar.gob.afip.wsfecred/FECredService/consultarTiposRetenciones")
    @WebResult(name = "consultarTiposRetencionesResponse", targetNamespace = "http://ar.gob.afip.wsfecred/FECredService/", partName = "parameters")
    public ConsultarTiposRetencionesResponseType consultarTiposRetenciones(

        @WebParam(partName = "parameters", name = "consultarTiposRetencionesRequest", targetNamespace = "http://ar.gob.afip.wsfecred/FECredService/")
        ConsultarCodigoDescripcionRequestType parameters
    );

    @WebMethod(action = "http://ar.gob.afip.wsfecred/FECredService/consultarHistorialEstadosCtaCte")
    @WebResult(name = "consultarHistorialEstadosCtaCteResponse", targetNamespace = "http://ar.gob.afip.wsfecred/FECredService/", partName = "parameters")
    public ConsultarHistorialEstadosCtaCteResponseType consultarHistorialEstadosCtaCte(

        @WebParam(partName = "parameters", name = "consultarHistorialEstadosCtaCteRequest", targetNamespace = "http://ar.gob.afip.wsfecred/FECredService/")
        ConsultarHistorialEstadosCtaCteRequestType parameters
    );

    /**
     * Método que permite obtener información sobre las transeferencias realizadas al Agente de Depósito
     * 				Colectivo.
     * 			
     */
    @WebMethod(action = "http://ar.gob.afip.wsfecred/FECredService/consultarFacturasAgtDptoCltv")
    @WebResult(name = "consultarFacturasAgtDptoCltvResponse", targetNamespace = "http://ar.gob.afip.wsfecred/FECredService/", partName = "parameters")
    public ConsultarFacturasAgtDptoCltvResponseType consultarFacturasAgtDptoCltv(

        @WebParam(partName = "parameters", name = "consultarFacturasAgtDptoCltvRequest", targetNamespace = "http://ar.gob.afip.wsfecred/FECredService/")
        ConsultarFacturasAgtDptoCltvRequestType parameters
    );

    @WebMethod(action = "http://ar.gob.afip.wsfecred/FECredService/modificarOpcionTransferencia")
    @WebResult(name = "modificarOpcionTransferenciaResponse", targetNamespace = "http://ar.gob.afip.wsfecred/FECredService/", partName = "parameters")
    public OperacionFECredResponseType modificarOpcionTransferencia(

        @WebParam(partName = "parameters", name = "modificarOpcionTransferenciaRequest", targetNamespace = "http://ar.gob.afip.wsfecred/FECredService/")
        ModificarOpcionTransferenciaRequestType parameters
    );
}
